method: emd
features:
  color_space: "HSV"
  bins: [16, 16, 16]
  preproc:
    resize: [256, 256]
    center_crop: [224, 224]
distance: "wasserstein"
ground_metric: "euclidean_xyz"
cache_dir: "artifacts/emd"
